/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package;

import java.awt.Color;
import java.awt.Component;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.swing.*;
import javax.swing.border.EmptyBorder;


/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {
    int posicao = 20;
    int posicao2 = 0;
    int qtdLabels = 1;
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        btnTriagem.setBackground(new Color(0,0,0,0));
        btnChamar.setBackground(new Color(0,0,0,0));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTriagem = new javax.swing.JButton();
        btnChamar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelSemScroll = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTriagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 384, 110, 34));

        btnChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarActionPerformed(evt);
            }
        });
        getContentPane().add(btnChamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 338, 110, 34));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 110, 50));

        jScrollPane1.setBorder(null);

        PainelSemScroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(PainelSemScroll);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 360, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imgFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JLabel jLabel1 = new javax.swing.JLabel();
        JLabel Nome = new javax.swing.JLabel();
        JLabel Idade = new javax.swing.JLabel();
        JLabel Sintomas = new javax.swing.JLabel();
        JLabel NumFila = new javax.swing.JLabel();
        JLabel Prioridade = new javax.swing.JLabel();
          
        Nome.setText("Nome");
        PainelSemScroll.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70,posicao2 +28, -1, -1));

        Idade.setText("Idade");
        PainelSemScroll.add(Idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, posicao2 +45, -1, -1));;

        Sintomas.setText("Sintomas");
        PainelSemScroll.add(Sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, posicao2 +61, -1, -1));

        NumFila.setText("N° na fila");
        PainelSemScroll.add(NumFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, posicao2 + 29, -1, -1));
        
        Prioridade.setText("Alta");
        PainelSemScroll.add(Prioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, posicao2 +61, -1, -1));
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PosicaoVermelha.png"))); // NOI18N
        PainelSemScroll.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, posicao, 386, 69));
        
        PainelSemScroll.revalidate();
        PainelSemScroll.repaint();
        posicao += 80;
        posicao2 += 80;
        qtdLabels +=1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriagemActionPerformed
        TelaTriagem TT = new TelaTriagem();
        TT.setVisible(true);
    }//GEN-LAST:event_btnTriagemActionPerformed

    private void btnChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarActionPerformed
        try {
            // Carregando o arquivo de áudio
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(TelaPrincipal.class.getResourceAsStream("/Audios/chamada"));

            // Obtendo o formato de áudio do arquivo
            AudioFormat format = audioInputStream.getFormat();

            // Configurando o clip de áudio
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            Clip clip = (Clip) AudioSystem.getLine(info);

            // Abrindo o clip de áudio
            clip.open(audioInputStream);

            // Reproduzindo o áudio
            clip.start();
            
            // Aguardando a reprodução terminar
            while (!clip.isRunning()){
                Thread.sleep(10);
            }
            while (clip.isRunning()){
                Thread.sleep(10);
            }

            // Fechando o stream e o clip
            clip.close();
            audioInputStream.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnChamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelSemScroll;
    private javax.swing.JButton btnChamar;
    private javax.swing.JButton btnTriagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
